import re
import subprocess
from pathlib import Path

import pytest

from music_agent import music

pytestmark = pytest.mark.mac


def test_read_real_library():
    tracks = music.read_library()
    assert len(tracks) > 0
    assert all(re.fullmatch(r"[0-9A-F]{16}", t.persistent_id) for t in tracks[:100])
    assert any(t.played_date is not None for t in tracks)


CLEANUP = Path(__file__).parent / "jxa" / "delete_playlist.js"
TEST_FOLDER = "zz music-agent test folder"
TEST_NAME = "zz music-agent test playlist"


def _cleanup():
    subprocess.run(
        ["osascript", "-l", "JavaScript", str(CLEANUP), TEST_NAME, f"{TEST_NAME} (fallback)",
         TEST_FOLDER],
        capture_output=True, text=True, check=False,
    )


def test_create_playlist_in_folder_and_report_missing():
    played = sorted(
        (t for t in music.read_library() if t.played_date is not None),
        key=lambda t: t.played_date,
        reverse=True,
    )[:3]
    ids = [t.persistent_id for t in played] + ["FFFFFFFFFFFFFFFF"]
    try:
        first = music.create_playlist(TEST_NAME, ids, TEST_FOLDER, f"{TEST_NAME} (fallback)")
        assert first.name == TEST_NAME
        assert first.track_count == 3
        assert first.missing_ids == ["FFFFFFFFFFFFFFFF"]
        second = music.create_playlist(TEST_NAME, ids[:1], TEST_FOLDER, f"{TEST_NAME} (fallback)")
        assert second.name == f"{TEST_NAME} (fallback)"
    finally:
        _cleanup()


def test_playlist_with_no_known_tracks_is_not_created():
    try:
        with pytest.raises(music.MusicError, match="None of the requested tracks"):
            music.create_playlist(TEST_NAME, ["FFFFFFFFFFFFFFFF"], TEST_FOLDER, f"{TEST_NAME} (x)")
        leftover = subprocess.run(
            ["osascript", "-l", "JavaScript", "-e",
             "const M=Application('Music'); String(M.playlists.whose({name: '"
             + TEST_NAME + "'}).length)"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
        assert leftover == "0"
    finally:
        _cleanup()


def test_name_and_description_stick_after_sync():
    """Regression: a rename right after creation reverted within seconds (iCloud keeps the
    creation name). Names and descriptions must be set at creation and still be there later."""
    import time

    played = next(t for t in music.read_library() if t.played_date is not None)
    try:
        created = music.create_playlist(
            TEST_NAME, [played.persistent_id], TEST_FOLDER, f"{TEST_NAME} (fallback)",
            description="One test track. Generated by music-agent.",
        )
        time.sleep(15)
        state = subprocess.run(
            ["osascript", "-l", "JavaScript", "-e",
             "const M=Application('Music'); const p=M.playlists.whose({persistentID: '"
             + created.persistent_id + "'})[0]; p.name() + '|' + p.description()"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
        assert state == f"{TEST_NAME}|One test track. Generated by music-agent."
    finally:
        _cleanup()
